In [1]:
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import random as rd
%matplotlib inline

In [2]:
import cv2
import numpy as np

In [3]:
def load_dict(filename):
    with open(filename) as f:
        data = f.readlines()
        data = [d[:98].strip() for d in data]
        
#         a=  [text_to_labels(d) for d in data]
#         print("data len:", str(len(data)))
#         print(a)
    return data

In [5]:
# dict_words = load_dict("./data/words_dict.txt")
# dict_words = rd.sample(dict_words, 5000)
# bank_name = load_dict("./data/banksName.txt")
# bank_bik = load_dict("./data/banksBik.txt")
# bank_acc = load_dict("./data/banksCorrAcc.txt")
# receiver_name = load_dict("./data/firmsNames.txt")
# other_words = ["Получатель", "Банк получателя", "БИК", "Сч. №", "ИНН", "КПП"]*100

In [6]:
# samples = bank_name + bank_bik + bank_acc + receiver_name + other_words + dict_words

In [13]:
# words = rd.sample(samples, 1000)

In [19]:
# words[:1000]

In [20]:
# with open("print_words.txt", "w") as f:
#     f.write("\n".join(words))

In [17]:
words = load_dict("./print_words.txt")

In [18]:
words[:1000]

['кусака',
 'ФИЛИАЛ "САМАРСКИЙ" АО "ОТП БАНК" г. САМАРА',
 '30101810600000000743',
 '30101810300000000448',
 'буерачный',
 'ультрафильтрация',
 'фехтование',
 'силуэтность',
 '040012002',
 'Сч. №',
 'потребовать',
 'бездомник',
 '30101810980730000948',
 'во всю мощь',
 'ускакнуть',
 '044525560',
 'потяжелеть',
 'Сч. №',
 'очеса',
 'свадьбище',
 '041403001',
 'извод',
 'Банк получателя',
 'огрести',
 'зарешечивать',
 'АРТ-БЛЕСК',
 '30101810045250000210',
 'АО АКБ "ЦЕНТРОКРЕДИТ" г. МОСКВА',
 'Гарнитура, ООО',
 '30101810400000000978',
 'Сч. №',
 'станкостроитель',
 '044525544',
 'рабовладелица',
 'тахеометрия',
 '30101810100000000922',
 'уширяться',
 'Банк получателя',
 'поварня',
 'настрачивание',
 '30101810900000000713',
 'понервничать',
 'Центр оценки авто',
 'проповедующийся',
 'Спецтехника ГрАЗ, ТД, ООО, представительство в г. Москве',
 'рекамбио',
 'ООО КБ "ЕВРОАЗИАТСКИЙ ИНВЕСТИЦИОННЫЙ БАНК" г. МОСКВА',
 '30101810900000000746',
 '044525094',
 'АО "СОЦИНВЕСТБАНК" г. УФА',
 'СИМФЕРОПО

In [48]:
a = np.array([[1,4,1],
              [3,1,5]])
# a = np.sort(a, axis=0,order=[1])                # sort along the last axis

a = a[a[:,1].argsort()][0]
a = np.expand_dims(a, axis=0)
print(a)
# np.sort(a, axis=None)     # sort the flattened array
# array([1, 1, 3, 4])
# np.sort(a, axis=0)        # sort along the first axis
# array([[1, 1],
#        [3, 4]])

[[3 1 5]]
